// Generated by CoffeeScript 1.6.1
(function() {

  this.application = new Application();

  this.editors = {};

  this.event = new Event();

  this.file_manager = new FileManager();

  this.mode = new Mode();

  this.util = new Util();

  $(function() {
    var editor;
    application.show_breadcrumb('/home/tyler/src/win/test/');
    application.show_sidebar('/home/tyler/src/win/test/');
    editor = new Editor('/home/tyler/src/win/test/111.py');
    return editors[editor.uid] = editor;
  });

}).call(this);
