// Generated by CoffeeScript 1.4.0
(function() {

  window.notice = function(title, content) {
    var notification;
    notification = window.webkitNotifications.createNotification('../icon/icon48.png', title, content);
    notification.show();
    return setTimeout((function() {
      return notification.cancel();
    }), 3000);
  };

}).call(this);
